name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Copiar archivos al servidor
        run: |
          rsync -av --delete ./ /var/www/laboratoriolinux/